export default[
    {
      id: 1,
      date:"September 7, 2020",
      img: 'https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/blog-5.jpg',
      title: '10 Reasons To Do A Digital Detox Challenge',
      name: 'namdam',
      description: 'Ac haca ullamcorper donec ante habi tasse donec imperdiet eturpis varius per a augue magna hac. Nec hac et vestibulum duis a tincidunt per a aptent interdum purus feugiat a id aliquet erat himenaeos nunc torquent euismod adipiscing adipiscing dui gravida justo.',
      moreInfo: 'Lorem ipsum dolor sit amet, ctetur adipisicing elit, sed do eiumod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sitvoluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto. beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia conse',
      thirdP: 'Lorem ipsum dolor sit amet, ctetur adipisicing elit, sed do eiumod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit.',
      quote: 'Champions keep playing until they get it right. I want my tennis to speak for everything. When you do something best in life, you don’t really want to give that up – and for me it’s tennis.',
      fourP: 'Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.'
    },
    {
      id: 2,
      date:"August 31, 2020",
      img: 'https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/blog-1.jpg',
      title: 'The Ultimate Hangover Burger: Egg in a Hole Burger Grilled Cheese',
      name: 'admin',
      description: 'Ac haca ullamcorper donec ante habi tasse donec imperdiet eturpis varius per a augue magna hac. Nec hac et vestibulum duis a tincidunt per a aptent interdum purus feugiat a id aliquet erat himenaeos nunc torquent euismod adipiscing adipiscing dui gravida justo.',
      moreInfo: 'Ultrices ut parturient morbi sit adipiscing sit a habitasse curabitur viverra at malesuada at vestibulum. Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.',
      thirdP: 'Netus pretium tellus nulla commodo massa adipiscing in elementum magna congue condimentum placerat habitasse potenti ac orci a quisque tristique elementum et viverra at condimentum scelerisque eu mi. Elit praesent cras vehicula a ullamcorper nulla scelerisque aliquet tempus faucibus quam ac aliquet nibh a condimentum suspendisse hac integer leo erat aliquam ut himenaeos.',
      quote: 'Quisque porttitor ipsum vitae fermentum suscipit. Praesent vel semper ello.',
      fourP: 'Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.'
    },
    {
      id: 3,
      date:"August 31, 2020",
      img: 'https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/blog-2.jpg',
      title: 'Traditional Soft Pretzels with Sweet Beer Cheese',
      name: 'admin',
      description: 'Ac haca ullamcorper donec ante habi tasse donec imperdiet eturpis varius per a augue magna hac. Nec hac et vestibulum duis a tincidunt per a aptent interdum purus feugiat a id aliquet erat himenaeos nunc torquent euismod adipiscing adipiscing dui gravida justo.',
      moreInfo: 'Ultrices ut parturient morbi sit adipiscing sit a habitasse curabitur viverra at malesuada at vestibulum. Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.',
      thirdP: 'Netus pretium tellus nulla commodo massa adipiscing in elementum magna congue condimentum placerat habitasse potenti ac orci a quisque tristique elementum et viverra at condimentum scelerisque eu mi. Elit praesent cras vehicula a ullamcorper nulla scelerisque aliquet tempus faucibus quam ac aliquet nibh a condimentum suspendisse hac integer leo erat aliquam ut himenaeos.',
      quote: 'Vestibulum tempor lobortis semper cras orci parturient a parturient tincidunt erat arcu sodales sed nascetur et mi bibendum condimentum suspendisse sodales nostra fermentum.undies.',
      fourP: 'Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.'
    },
    {
      id: 4,
      date:"September 7, 2020",
      img: 'https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/blog-3.jpg',
      title: 'My Favorite Easy Black Pizza Toast Recipe',
      name: 'admin',
      description: 'Ac haca ullamcorper donec ante habi tasse donec imperdiet eturpis varius per a augue magna hac. Nec hac et vestibulum duis a tincidunt per a aptent interdum purus feugiat a id aliquet erat himenaeos nunc torquent euismod adipiscing adipiscing dui gravida justo.',
      moreInfo: 'Ultrices ut parturient morbi sit adipiscing sit a habitasse curabitur viverra at malesuada at vestibulum. Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.',
      thirdP: 'Netus pretium tellus nulla commodo massa adipiscing in elementum magna congue condimentum placerat habitasse potenti ac orci a quisque tristique elementum et viverra at condimentum scelerisque eu mi. Elit praesent cras vehicula a ullamcorper nulla scelerisque aliquet tempus faucibus quam ac aliquet nibh a condimentum suspendisse hac integer leo erat aliquam ut himenaeos.',
      quote: 'Vestibulum tempor lobortis semper cras orci parturient a parturient tincidunt erat arcu sodales sed nascetur et mi bibendum condimentum suspendisse sodales nostra fermentum.undies.',
      fourP: 'Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.'
    },
    {
      id: 5,
      date:"September 7, 2020",
      img: 'https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/blog-4.jpg',
      title: '6 Ingredient Vegan Cinnamon Rolls',
      name: 'admin',
      description: 'Ac haca ullamcorper donec ante habi tasse donec imperdiet eturpis varius per a augue magna hac. Nec hac et vestibulum duis a tincidunt per a aptent interdum purus feugiat a id aliquet erat himenaeos nunc torquent euismod adipiscing adipiscing dui gravida justo.',
      moreInfo: 'Ultrices ut parturient morbi sit adipiscing sit a habitasse curabitur viverra at malesuada at vestibulum. Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.',
      thirdP: 'Netus pretium tellus nulla commodo massa adipiscing in elementum magna congue condimentum placerat habitasse potenti ac orci a quisque tristique elementum et viverra at condimentum scelerisque eu mi. Elit praesent cras vehicula a ullamcorper nulla scelerisque aliquet tempus faucibus quam ac aliquet nibh a condimentum suspendisse hac integer leo erat aliquam ut himenaeos.',
      quote: 'Vestibulum tempor lobortis semper cras orci parturient a parturient tincidunt erat arcu sodales sed nascetur et mi bibendum condimentum suspendisse sodales nostra fermentum.undies.',
      fourP: 'Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.'
    },
    {
      id: 6,
      date:"September 7, 2020",
      img: 'https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/blog-5.jpg',
      title: 'Addictive Appetizers: Sausage Cheese Balls',
      name: 'admin',
      description: 'Ac haca ullamcorper donec ante habi tasse donec imperdiet eturpis varius per a augue magna hac. Nec hac et vestibulum duis a tincidunt per a aptent interdum purus feugiat a id aliquet erat himenaeos nunc torquent euismod adipiscing adipiscing dui gravida justo.',
      moreInfo: 'Ultrices ut parturient morbi sit adipiscing sit a habitasse curabitur viverra at malesuada at vestibulum. Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.',
      thirdP: 'Netus pretium tellus nulla commodo massa adipiscing in elementum magna congue condimentum placerat habitasse potenti ac orci a quisque tristique elementum et viverra at condimentum scelerisque eu mi. Elit praesent cras vehicula a ullamcorper nulla scelerisque aliquet tempus faucibus quam ac aliquet nibh a condimentum suspendisse hac integer leo erat aliquam ut himenaeos.',
      quote: 'Vestibulum tempor lobortis semper cras orci parturient a parturient tincidunt erat arcu sodales sed nascetur et mi bibendum condimentum suspendisse sodales nostra fermentum.undies.',
      fourP: 'Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.'
    },
    {
      id: 7,
      date:"September 7, 2020",
      img: 'https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/blog-6.jpg',
      title: 'Crispy Stovetop Roasted Red Potatoes',
      name: 'admin',
      description: 'Ac haca ullamcorper donec ante habi tasse donec imperdiet eturpis varius per a augue magna hac. Nec hac et vestibulum duis a tincidunt per a aptent interdum purus feugiat a id aliquet erat himenaeos nunc torquent euismod adipiscing adipiscing dui gravida justo.',
      moreInfo: 'Ultrices ut parturient morbi sit adipiscing sit a habitasse curabitur viverra at malesuada at vestibulum. Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.',
      thirdP: 'Netus pretium tellus nulla commodo massa adipiscing in elementum magna congue condimentum placerat habitasse potenti ac orci a quisque tristique elementum et viverra at condimentum scelerisque eu mi. Elit praesent cras vehicula a ullamcorper nulla scelerisque aliquet tempus faucibus quam ac aliquet nibh a condimentum suspendisse hac integer leo erat aliquam ut himenaeos.',
      quote: 'Vestibulum tempor lobortis semper cras orci parturient a parturient tincidunt erat arcu sodales sed nascetur et mi bibendum condimentum suspendisse sodales nostra fermentum.undies.',
      fourP: 'Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.'
    },
    {
      id: 8,
      date:"September 7, 2020",
      img: 'https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/blog-7.jpg',
      title: 'Easy 4 Ingredient Hatch Salsa Verde',
      name: 'admin',
      description: 'Ac haca ullamcorper donec ante habi tasse donec imperdiet eturpis varius per a augue magna hac. Nec hac et vestibulum duis a tincidunt per a aptent interdum purus feugiat a id aliquet erat himenaeos nunc torquent euismod adipiscing adipiscing dui gravida justo.',
      moreInfo: 'Ultrices ut parturient morbi sit adipiscing sit a habitasse curabitur viverra at malesuada at vestibulum. Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.',
      thirdP: 'Netus pretium tellus nulla commodo massa adipiscing in elementum magna congue condimentum placerat habitasse potenti ac orci a quisque tristique elementum et viverra at condimentum scelerisque eu mi. Elit praesent cras vehicula a ullamcorper nulla scelerisque aliquet tempus faucibus quam ac aliquet nibh a condimentum suspendisse hac integer leo erat aliquam ut himenaeos.',
      quote: 'Vestibulum tempor lobortis semper cras orci parturient a parturient tincidunt erat arcu sodales sed nascetur et mi bibendum condimentum suspendisse sodales nostra fermentum.undies.',
      fourP: 'Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.'
    },
    {
      id: 9,
      date:"September 7, 2020",
      img: 'https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/blog-8.jpg',
      title: 'Totoro Pancake Tutorial: Easy Totoro Pancake Food Art',
      name: 'admin',
      description: 'Ac haca ullamcorper donec ante habi tasse donec imperdiet eturpis varius per a augue magna hac. Nec hac et vestibulum duis a tincidunt per a aptent interdum purus feugiat a id aliquet erat himenaeos nunc torquent euismod adipiscing adipiscing dui gravida justo.',
      moreInfo: 'Ultrices ut parturient morbi sit adipiscing sit a habitasse curabitur viverra at malesuada at vestibulum. Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.',
      thirdP: 'Netus pretium tellus nulla commodo massa adipiscing in elementum magna congue condimentum placerat habitasse potenti ac orci a quisque tristique elementum et viverra at condimentum scelerisque eu mi. Elit praesent cras vehicula a ullamcorper nulla scelerisque aliquet tempus faucibus quam ac aliquet nibh a condimentum suspendisse hac integer leo erat aliquam ut himenaeos.',
      quote: 'Vestibulum tempor lobortis semper cras orci parturient a parturient tincidunt erat arcu sodales sed nascetur et mi bibendum condimentum suspendisse sodales nostra fermentum.undies.',
      fourP: 'Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.'
    },
    {
      id: 10,
      date:"September 7, 2020",
      img: 'https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/blog-9.jpg',
      title: 'How to Make Jammy Soft Boiled Eggs at Home',
      name: 'admin',
      description: 'Ac haca ullamcorper donec ante habi tasse donec imperdiet eturpis varius per a augue magna hac. Nec hac et vestibulum duis a tincidunt per a aptent interdum purus feugiat a id aliquet erat himenaeos nunc torquent euismod adipiscing adipiscing dui gravida justo.',
      moreInfo: 'Ultrices ut parturient morbi sit adipiscing sit a habitasse curabitur viverra at malesuada at vestibulum. Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.',
      thirdP: 'Netus pretium tellus nulla commodo massa adipiscing in elementum magna congue condimentum placerat habitasse potenti ac orci a quisque tristique elementum et viverra at condimentum scelerisque eu mi. Elit praesent cras vehicula a ullamcorper nulla scelerisque aliquet tempus faucibus quam ac aliquet nibh a condimentum suspendisse hac integer leo erat aliquam ut himenaeos.',
      quote: 'Vestibulum tempor lobortis semper cras orci parturient a parturient tincidunt erat arcu sodales sed nascetur et mi bibendum condimentum suspendisse sodales nostra fermentum.undies.',
      fourP: 'Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.'
    },
    {
      id: 11,
      date:"September 7, 2020",
      img: 'https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/blog-10.jpg',
      title: 'Small Batch Triple Cheese Loaf Sandwiches',
      name: 'admin',
      description: 'Ac haca ullamcorper donec ante habi tasse donec imperdiet eturpis varius per a augue magna hac. Nec hac et vestibulum duis a tincidunt per a aptent interdum purus feugiat a id aliquet erat himenaeos nunc torquent euismod adipiscing adipiscing dui gravida justo.',
      moreInfo: 'Ultrices ut parturient morbi sit adipiscing sit a habitasse curabitur viverra at malesuada at vestibulum. Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.',
      thirdP: 'Netus pretium tellus nulla commodo massa adipiscing in elementum magna congue condimentum placerat habitasse potenti ac orci a quisque tristique elementum et viverra at condimentum scelerisque eu mi. Elit praesent cras vehicula a ullamcorper nulla scelerisque aliquet tempus faucibus quam ac aliquet nibh a condimentum suspendisse hac integer leo erat aliquam ut himenaeos.',
      quote: 'Vestibulum tempor lobortis semper cras orci parturient a parturient tincidunt erat arcu sodales sed nascetur et mi bibendum condimentum suspendisse sodales nostra fermentum.undies.',
      fourP: 'Leo duis lacinia placerat parturient montes vulputate cubilia posuere parturient inceptos massa euismod curabitur dis dignissim vestibulum quam a urna.'
    },
]